### ISSUE TITLE
Find ideas on addressing namespaced attributes

### ISSUE THREAD

**Issue by funkyfuture** [funkyfuture/delb#17]
i found this in the wild:

```python
tag('cit', {f'{{{XML_NS}}}lang': lang})
```

i don't like it. there must be a better way.

i'm worried to eventually introduce a data type for qualified names. maybe a combination of an attributes adapter and a string subclass yields slick uses.

**Comment by funkyfuture** [comment]
# Design of a smarter attribute access with delb

## Current problems

### Namespaces

```python
>>> r = Document('<root foo="f" xml:id="1234" xmlns:ex="https://ex.org" ex:bar="b" />').root
>>> r.attributes
{'foo': 'f', '{http://www.w3.org/XML/1998/namespace}id': 'id', '{https://ex.org}bar': 'b'}
>>> r.attributes["foo"]
'f'
>>> r.attributes["xml:id"]
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    r.attributes["xml:id"]
  File "src/lxml/etree.pyx", line 2479, in lxml.etree._Attrib.__getitem__
KeyError: 'xml:id'
>>> r.attributes["{http://www.w3.org/XML/1998/namespace}id"]
'1234'
```

- namespaced attributes are accessible by Clark notation only
    - which makes it bad to read with f-strings
- whether an attribute belongs to a namespace or not can only be tested with `startswith`; that is also bloated with curly brackets when f-strings are used

```python
>>> r = Document('<root xmlns="http://default" foo="bar" />').root
>>> r.attributes
{'foo': 'bar'}
>>> r["foo"]
'bar'
>>> r = Document('<root xmlns="http://default.one"><child xmlns:one="http://default.one" xmlns="https://default.two" one:foo1="bar1" foo2="bar2"/></root>').root
>>> r.first_child.attributes
{'{http://default.one}foo1': 'bar1', 'foo2': 'bar2'}
>>> r.attributes["{http://default.one}test"] = "fjksd"
>>> str(r)
'<root xmlns="http://default.one" xmlns:ns0="http://default.one" ns0:test="fjksd"><child xmlns="https://default.two" ns0:foo1="bar1" foo2="bar2"/></root>'
```

- this is inconsistent in lxml or libxml2, but actually intuitive when a node and its attribute are in the same namespace

### Changing namespace and/or local name

as with any Python mapping, changes to a key, involve removing the item and adding the value with a new key.

## Proposals

### Getting and setting namespaced attributes

a namespaced attribute can be retrieved or set by either the Clark notation or by providing a tuple of a namespace and name. when a single string is given, the node's namespace is used (possibly none).

```python
>>> node.namespace
"http://example.org/"
>>> # these are equivalent
>>> node.attributes["foo"] = "bar"
>>> node.attributes["{https://example.org/}foo")] = "bar"
>>> namespace = "https://example.org"
>>> node.attributes[(namespace, f"f{2*'o'}")] = "bar"
```

### Manipulating an attribute

instead of a built-in string, a subclass of `collections.UserString` will be returned as value. beside its usage as string, it acts as proxy to conveniently test and manipulate the whole attribute.

```python
>>> attribute = node.attributes["foo"]
>>> attribute.namespace
"https://example.org"
>>> attribute.namespace = "https://magic.carpet"
>>> attribute.namespace = None
>>> attribute.local_name
"foo"
>>> attribute.local_name = "bar"
>>> attribute.value
"one"
>>> attribute.value = "two"
```

**Comment by funkyfuture** [comment]
an alternate option to providing an attribute's namespace and name with tuples could be to use the slice syntax (see last line of the first proposal's example above):

```python
>>> node.attributes[namespace:f"b{2*'o'}"] = "far"
```
